### ISSUE TITLE
Log events using signals

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#105]
Log events using django signals instead of overwriting the view.

## Description

Doc: 
 * Signals: https://docs.djangoproject.com/en/3.2/topics/signals/
 * Receive signals: https://docs.djangoproject.com/en/3.2/topics/signals/#listening-to-signals

Remove the `logs/view_mixin.py` file and log from models signals, so we can also log events comming from the admin page maybe ? or make ir an option.

## TODO

- [x] Remove `logs/view_mixin.py`
- [x] Add custom signals for specific actions (start_build, start_deploy...)
  - [x] Deploy app
    - [x] Auto deploy started
    - [x] Deploy started
    - [x] Deploy success
    - [x] Deploy failed
  - [x] Build app
    - [x] Auto build started
    - [x] Build started
    - [x] Build successful
    - [x] Build failed
- [x] Log events from Django signals

Ideas:
- [ ] Add option not to log admin pannel actions

Note that "regular" signals (create, update, delete) are used for all the other actions, the listed are only the custom one.
