### ISSUE TITLE
Change the default TEST_RUNNER

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#109]
Create a custom test runner class (https://docs.djangoproject.com/en/3.2/topics/testing/advanced/#defining-a-test-runner) and change the `teardown_test_environment` (https://docs.djangoproject.com/en/3.2/topics/testing/advanced/#django.test.runner.DiscoverRunner.teardown_test_environment) function to delete the `TEST_ROOT` folder.
Set the test runner has default: https://docs.djangoproject.com/en/3.2/ref/settings/#test-runner.

## TODO

- [ ] Create custom test runner
- [ ] Set it has default in settings (`TEST_RUNNER`)
- [ ] Change `teardown_test_environment` to delete the test dir
- [ ] Change `setup_test_environment` to set the value of `MEDIA_ROOT` to `TEST_ROOT`
