### ISSUE TITLE
Add celery for the build and deploy proccess

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#112]
https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

Setup the celery worker, add it to docker, add tasks.

## TODO

- [ ] Setup celery
  - [ ] Requirements
  - [ ] Celery settings
  - [ ] Add celery to docker-compose
    - [ ] Create a docker-compose for the API only
    - [ ] Add to the main docker-compose
- [ ] Create build celery task (that just do a `time.sleep(10)` for now)
- [ ] Create deploy celery task (that just do a `time.sleep(10)` for now)
