### ISSUE TITLE
Add the ability to block burner email

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#115]
https://github.com/wesbos/burner-email-providers

Add the ability to validate and block burners emails.

## TODO

- [ ] Add the repo has a submodule
- [ ] Create utils to detect burner
- [ ] Overwrite the email validator
