### ISSUE TITLE
404 page is always looking the same

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#132]
Right now the 404 page is just a component "called" when no route has been detected ex:

in file `pages/IPFSDapp/IPFSDapp.tsx`:
```
<Router>
      <Dappbar dapp={dapp} />
          [...]
          <Route path={`${path}/source`} component={IPFSDappSource} />
          <Route path="*" component={NotFound} />
        </Switch>
</Router>
```

In this example the `Dappbar` component is out of the switch because it need's to be on every sub pages (deploy, settings, etc.) for navigation, except on the 404.

We can't redirect because the URL would change and the user needs to be able to go back and/or see the URL.

The navbar need's to be present to change page be nothing else.

## TODO

- [ ] Make the 404 page look the same everywhere.
- [ ] Navbar present on 404 page.
- [ ] Return a 404 HTTP response for the browser.
