### ISSUE TITLE
403 page

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#133]
Add other error pages.

## TODO

- [ ] Add 403 page works like 404.
  - [ ] Return 403 code to browser.
  - [ ] Look the same everywhere.
