### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#134]
Add dark mode and make components compatible with it.

## TODO

- [ ] Dark mode global context
- [ ] Dark mode switch.
- [ ] Dark mode on components.

**Comment by 2O4** [comment]
https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
