### ISSUE TITLE
Add 'sensitive' option on env var

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#135]
Add a "sensitive" env var option to mark them as write-only.

In Django admin: add a write-only field so that the user can only modify or create a sensitive envvar.

## Example

In `django/contrib/auth/forms` there is a `ReadOnlyPasswordHashField` and a widget used for the admin site.

## TODO

- [x] Add sensitive to envvar models
- [x] Change the serializers to hide sensitive env vars
- [x] Sensitive should be **CREATE** and **read** only
- [ ] Block their view from Django admin
- [ ] Add tests
