### ISSUE TITLE
Style toast from Tailwind

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#140]
Following: #120

Style toast with the default tailwind colors from the `tailwind.config.js`.

https://fkhadra.github.io/react-toastify/how-to-style#passing-css-classes-to-component
https://fkhadra.github.io/react-toastify/how-to-style#css-classes-as-function

- `success`: `bg-green-400`
- `info`: `bg-blue-400`
- `warning`: `bg-yellow-400`
- `error`: `bg-red-400`

# TODO

- [x] Remove the default 'fancy-progress-bar'
- [x] Style toast with tailwind's config colors with a CSS classe
- [x] Create a custom toast component with a retry button
- [x] Place the toast on bottom right of the screen by default
